(function () {
  const app = document.querySelector("#app"), m = window.MISSION_01;
  const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent) || (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1);
  const NORMAL_RATE = 1, SLOW_RATE = isIOS ? .58 : .72, letters = ["A", "B", "C", "D"];
  let run = null, videoStageCleanup = null, fullVideoStage = null, hasEnteredFullSimulation = false;
  const activeTimers = new Set();
  const esc = value => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const shuffle = list => { const copy = [...list]; for (let i = copy.length - 1; i; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
  const all = group => m.scenarios.filter(item => item.group === group);
  const ids = group => all(group).map(item => item.id);
  const scenario = id => m.scenarios.find(item => item.id === id);
  const tripRows = () => m.tripProfile.map(([label, english, chinese]) => `<div><span>${label}</span><strong>${english}</strong><small>${chinese}</small></div>`).join("");
  function addOfficerPhoto(avatar) { if (!avatar) return; avatar.classList.add("officer-photo"); const image = document.createElement("img"); image.src = "assets/mission-01/immigration-officer.jpeg"; image.alt = "Immigration Officer"; image.addEventListener("error", () => { avatar.classList.remove("officer-photo"); avatar.textContent = "👤"; }); avatar.replaceChildren(image); }
  const schedule = (callback, delay) => { let timerId = null; timerId = window.setTimeout(() => { activeTimers.delete(timerId); callback(); }, delay); activeTimers.add(timerId); return timerId; };
  const cancelTimer = timerId => { if (!timerId) return; window.clearTimeout(timerId); activeTimers.delete(timerId); };
  const clearActiveTimers = () => { activeTimers.forEach(timerId => window.clearTimeout(timerId)); activeTimers.clear(); };
  const exitButtonMarkup = (label = "結束並返回首頁", isEntry = false) => `<footer class="exit-home-footer${isEntry ? " entry-exit-action" : ""}"><button class="text-button exit-home-button" data-a="home">${label}</button></footer>`;
  const canExitQuestion = () => Boolean(run?.picks?.[run.index]?.turn?.isInteractive);
  function addExitHomeButton() { const screen = app.querySelector(".screen"); if (!screen || screen.classList.contains("home-screen") || screen.classList.contains("lesson-screen") || screen.matches(".adjustment-screen, .approach-screen, .counter-arrival, .video-stage")) return; if (screen.classList.contains("question-screen") && !canExitQuestion()) return; const completed = screen.classList.contains("results-screen"), isEntry = screen.classList.contains("trip-screen"), label = completed ? "返回首頁" : "結束並返回首頁", homeButtons = [...app.querySelectorAll('[data-a="home"]')]; if (homeButtons.length) { homeButtons.slice(0, -1).forEach(button => button.remove()); const button = homeButtons.at(-1); button.textContent = label; button.classList.add("exit-home-button"); const footer = document.createElement("footer"); footer.className = `exit-home-footer${isEntry ? " entry-exit-action" : ""}`; button.replaceWith(footer); footer.append(button); return; } screen.insertAdjacentHTML("beforeend", exitButtonMarkup(label, isEntry)); }
  const renderView = (html, { scrollTop = true } = {}) => { if (videoStageCleanup) videoStageCleanup(); app.innerHTML = html; addExitHomeButton(); app.querySelectorAll(".officer-visual, .full-question-screen .counter-avatar, .full-ending .counter-avatar").forEach(addOfficerPhoto); if (scrollTop) window.scrollTo({ top: 0, behavior: "auto" }); };
  const audioButton = (text, role = "user", label = "播放英文") => `<button aria-label="${label}" data-a="speak" data-role="${role}" data-text="${esc(text)}">🔊</button>`;
  const progress = () => missionStorage.getProgress();
  const count = (p, group) => (group === "core" ? p.coreMasteredScenarioIds : p.extensionMasteredScenarioIds).length;
  const groupName = group => group === "core" ? "核心入境挑戰" : "延伸入境挑戰";
  const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
  const sameSet = (a, b) => a.length === b.length && a.every(id => b.includes(id));
  const fullRank = { passport: 0, purpose: 1, length: 2, accommodation: 2, companion: 3, previous_visit: 3, occupation: 3, departure: 4, return_ticket: 4, local_contact: 5, trip_payment: 5, trip_plan: 5 };
  function buildFullSimulation() {
    const requiredIds = ["passport", "purpose", "length", "accommodation"], variable = m.scenarios.filter(item => !requiredIds.includes(item.id));
    const previous = progress().lastFullSimulationScenarioIds || []; let selected = [], target = 6;
    for (let attempt = 0; attempt < 5; attempt++) {
      target = randomInt(6, 8);
      selected = [...requiredIds.map(scenario), ...shuffle(variable).slice(0, target - requiredIds.length)];
      if (!sameSet(selected.map(item => item.id).sort(), [...previous].sort())) break;
    }
    const passport = selected.find(item => item.id === "passport"), purpose = selected.find(item => item.id === "purpose");
    const rest = shuffle(selected.filter(item => item.id !== "passport" && item.id !== "purpose")).sort((a, b) => fullRank[a.id] - fullRank[b.id]);
    return [passport, purpose, ...rest];
  }

  const isSimulationInProgress = () => Boolean(run?.picks && !run.finished);
  function closeExitConfirmation() { app.querySelector(".exit-confirmation")?.remove(); }
  function showExitConfirmation() { if (app.querySelector(".exit-confirmation")) return; app.insertAdjacentHTML("beforeend", `<section class="exit-confirmation" role="dialog" aria-modal="true" aria-labelledby="exit-confirmation-title"><div class="exit-confirmation-card"><h2 id="exit-confirmation-title">確定要結束嗎？</h2><p>目前的答題進度將不會計入本次結果。</p><div><button class="button button-quiet" data-a="continue-exit">繼續作答</button><button class="button button-primary" data-a="confirm-exit">結束並返回首頁</button></div></div></section>`); }
  function exitToHome() { const turn = run?.picks?.[run.index]?.turn; if (turn) { clearRevealTimer(turn); turn.audioToken += 1; } clearActiveTimers(); missionAudio.stop(); if (videoStageCleanup) videoStageCleanup(); hasEnteredFullSimulation = false; run = null; closeExitConfirmation(); home(); }
  function requestExitToHome() { if (isSimulationInProgress()) showExitConfirmation(); else exitToHome(); }
  function stopPageActivity() { clearActiveTimers(); missionAudio.stop(); if (videoStageCleanup) videoStageCleanup(); }

  function home() {
    if (run?.picks?.[run.index]?.turn) clearRevealTimer(run.picks[run.index].turn); missionAudio.stop(); run = null; const p = progress(), core = count(p, "core"), ext = count(p, "extension");
    const coreCopy = core === 8 ? "已完成核心入境情境" : core ? `還有 ${8 - core} 個情境等你完成` : "8個最重要的入境情境";
    const extension = p.extensionUnlocked ? `<article class="progress-step is-open"><p>STEP 2 <em>NEW</em></p><strong>延伸入境挑戰</strong><small>4個新的入境詢問情境</small><b>延伸進度 ${ext} / 4</b><button class="button button-primary" data-a="simulate-extension">${ext ? "繼續挑戰" : "開始延伸挑戰"}</button></article>` : `<article class="progress-step is-locked"><p>STEP 2</p><strong>延伸入境挑戰</strong><small>${core ? `再完成 ${8 - core} 個核心情境即可解鎖` : "完成8個核心情境後解鎖"}</small><b>🔒</b></article>`;
    const full = p.fullSimulationUnlocked ? `<article class="progress-step is-open"><p>STEP 3</p><strong>完整入境模擬</strong><small>你已經練過12種入境情境。每次都可能遇到不同的問題與問法。</small><b>已解鎖</b><button class="button button-primary" data-a="full-intro">開始完整模擬</button></article>` : `<article class="progress-step is-locked"><p>STEP 3</p><strong>完整入境模擬</strong><small>完成核心與延伸挑戰後解鎖</small><b>🔒</b></article>`;
    renderView(`<section class="screen home-screen"><div class="mission-badge">🛂 ${m.eyebrow}</div><h1>${m.title}</h1><p class="lead">你剛抵達國外機場。能聽懂、能回應、能把事情辦完就好。</p><div class="entry-cards"><button class="entry-card" data-a="learn"><span>📖</span><strong>學習如何入境</strong><small>先看看入境官可能會問什麼，學會怎麼回答。</small></button></div><section class="progression"><article class="progress-step is-core"><p>STEP 1</p><strong>核心入境挑戰</strong><small>${coreCopy}</small><b>核心進度 ${core} / 8</b><button class="button button-primary" data-a="simulate-core">${core ? (core === 8 ? "再次模擬" : "繼續挑戰") : "開始模擬"}</button></article>${extension}${full}</section></section>`);
  }
  function learn() { renderView(`<section class="screen"><p class="eyebrow">LEARN IMMIGRATION</p><h1>學習如何入境</h1><p class="lead">12 個情境都可以先自由學習。</p><div class="scenario-list">${m.scenarios.map((item, i) => `<button class="scenario-item" data-a="lesson" data-id="${item.id}"><span>${String(i + 1).padStart(2, "0")}</span><div><strong>${item.icon} ${item.title}</strong><small>${item.intentHint}</small></div><b>›</b></button>`).join("")}</div><button class="review-toggle" data-a="survival">🛟 聽不懂怎麼辦？</button><button class="text-button" data-a="home">返回首頁</button></section>`); }
  const learnPhraseContent = answer => `${audioButton(answer.text)}<div class="learn-phrase"><strong>${answer.text}</strong><small>${answer.zh}</small></div>`;
  function answerContent(v) { return v.answerType === "action" ? `<div class="answer-levels"><span>你要做的事</span><strong>${v.learnAnswers.action.text}</strong><small class="learn-action-translation">${v.learnAnswers.action.zh}</small><div><span>可以說</span>${learnPhraseContent(v.learnAnswers.sentence)}</div></div>` : `<div class="answer-levels"><div><span>簡易回答</span>${learnPhraseContent(v.learnAnswers.simple)}</div><div><span>句子回答</span>${learnPhraseContent(v.learnAnswers.sentence)}</div></div>`; }
  function variantCard(v) { return `<article class="variant">${audioButton(v.text, "officer", "播放英文問題")}<div><strong>${v.text}</strong><small>${v.zhMeaning}</small>${answerContent(v)}</div></article>`; }
  function lesson(id) { const item = scenario(id), topicNumber = m.scenarios.findIndex(topic => topic.id === id) + 1, visibleCount = item.group === "extension" ? 3 : 4, visible = item.variants.slice(0, visibleCount), hidden = item.variants.slice(visibleCount); renderView(`<section class="screen lesson-screen"><p class="eyebrow">${item.icon} ${item.title}｜第 ${topicNumber}／${m.scenarios.length} 類</p><h1>${item.title}</h1><p class="lead">他想知道：<br><strong>${item.intentHint}</strong></p><div class="lesson-answer">${answerContent(item.variants[0])}</div><h2>🎧 常見問法</h2>${visible.map(variantCard).join("")}${hidden.length ? `<div id="more-variants" hidden>${hidden.map(variantCard).join("")}</div><button class="review-toggle compact-toggle" data-a="toggle-variants">查看更多問法 ▾</button>` : ""}<p class="lesson-tip">不用每個字都聽懂。你真正要知道的是：${item.intentHint}</p>${item.alternatives?.length ? `<div class="alternatives"><span>如果你的情況不一樣</span><div id="more-answers" hidden>${item.alternatives.map(answer => `<div class="alternative-answer">${learnPhraseContent(answer)}</div>`).join("")}</div><button class="text-button inline-toggle" data-a="toggle-answers">查看更多回答 ▾</button></div>` : ""}<button class="text-button" data-a="learn">收合此主題，返回情境列表</button></section>`); }
  function survival() { renderView(`<section class="screen briefing-screen"><p class="eyebrow">🛟 SURVIVAL ENGLISH</p><h1>聽不懂怎麼辦？</h1>${m.survival.map(([english, chinese]) => `<article class="variant">${audioButton(english)}<div><strong>${english}</strong><small>${chinese}</small></div></article>`).join("")}<button class="text-button" data-a="learn">返回學習</button></section>`); }
  function trip(group) { renderView(`<section class="screen trip-screen"><p class="eyebrow">✈️ ${group === "core" ? "CORE 8" : "EXTENSION 4"}</p><h1>你的旅行資料</h1><p class="lead">這是這次入境需要用到的資料。</p><div class="trip-card">${tripRows()}</div><button class="button button-primary button-large" data-a="start" data-group="${group}">開始 ${group === "core" ? "8 題核心入境" : "4 題延伸入境"}</button><button class="text-button" data-a="home">返回首頁</button></section>`); }
  function start(group) { clearActiveTimers(); missionAudio.stop(); const scenarios = all(group); run = { group, index: 0, results: [], picks: scenarios.map(item => ({ scenario: item, variant: item.variants[Math.floor(Math.random() * item.variants.length)] })), finished: false }; challenge(true, true); }
  function fullIntro() { renderView(`<section class="screen trip-screen full-intro"><p class="eyebrow">🛂 FULL SIMULATION</p><h1>完整入境模擬</h1><p class="lead">這次不會告訴你會遇到哪些問題。聽清楚、做出回應，把這次入境完成就好。</p><div class="trip-card">${tripRows()}</div><button class="button button-primary button-large" data-a="start-full">走向入境櫃檯 →</button><button class="text-button" data-a="home">返回首頁</button></section>`); }
  function startFull() { clearActiveTimers(); missionAudio.stop(); const scenarios = buildFullSimulation(); hasEnteredFullSimulation = false; run = { group: "full", index: 0, results: [], picks: scenarios.map(item => ({ scenario: item, variant: item.variants[Math.floor(Math.random() * item.variants.length)] })), fullScenarioIds: scenarios.map(item => item.id), finished: false }; playFullIntroVideo(); }
  function enterFullSimulationQuestions() { if (hasEnteredFullSimulation || !run || run.group !== "full") return; hasEnteredFullSimulation = true; const stage = document.querySelector("#full-video-stage"); if (videoStageCleanup) videoStageCleanup(); stage?.classList.add("is-leaving"); schedule(() => { if (run?.group === "full" && hasEnteredFullSimulation) challenge(true, true); }, 360); }
  function playFullIntroVideo() {
    renderView(`<section class="screen video-stage" id="full-video-stage"><video id="full-intro-video" class="full-intro-video" aria-label="走向入境審查櫃檯的情境影片" playsinline preload="metadata"><source src="assets/mission-01/full-simulation-intro.mp4" type="video/mp4"></video><p class="video-status" id="video-status">情境載入中…</p><button class="text-button video-skip" id="video-skip">略過影片</button></section>`);
    const video = document.querySelector("#full-intro-video"), status = document.querySelector("#video-status"), skipButton = document.querySelector("#video-skip");
    const ready = () => { if (status) status.hidden = true; };
    const fail = () => { if (status) { status.hidden = false; status.textContent = "影片無法播放，直接開始模擬"; } if (skipButton) skipButton.textContent = "直接開始"; };
    const skip = () => enterFullSimulationQuestions();
    const cleanup = () => { if (!video) return; video.pause(); video.removeEventListener("ended", enterFullSimulationQuestions); video.removeEventListener("error", fail); video.removeEventListener("canplay", ready); video.removeEventListener("playing", ready); skipButton?.removeEventListener("click", skip); if (videoStageCleanup === cleanup) videoStageCleanup = null; if (fullVideoStage?.cleanup === cleanup) fullVideoStage = null; };
    videoStageCleanup = cleanup; fullVideoStage = { cleanup };
    video.addEventListener("ended", enterFullSimulationQuestions); video.addEventListener("error", fail); video.addEventListener("canplay", ready); video.addEventListener("playing", ready); skipButton?.addEventListener("click", skip);
    try { const playPromise = video.play(); if (playPromise?.catch) playPromise.catch(fail); } catch (error) { console.warn("Full Simulation intro video playback failed.", error); fail(); }
  }
  const active = () => run.picks[run.index];
  function initTurn() { const pick = active(); if (!pick.turn) pick.turn = { conversation: pick.variant, options: shuffle(pick.variant.options), correctOptionId: pick.variant.correctOptionId, repeat: 0, slow: 0, subtitle: false, travelHintOpen: false, wrong: 0, recoveryLevel: 0, firstAttemptConfidence: null, firstAttemptCorrect: null, officerRephrased: false, firstListenCompleted: false, activeRecall: false, responseReady: false, responseJustRevealed: false, responseRevealTimer: null, audioRetryNeeded: false, audioRetryAttempted: false, audioState: "speaking", isInteractive: false, audioToken: 0 }; return pick.turn; }
  function setConversation(turn, next) { if (!next) return false; const changed = turn.conversation.id !== next.id, same = turn.options.map(o => o.text).sort().join("|") === next.options.map(o => o.text).sort().join("|"); turn.conversation = next; if (changed && !same) turn.options = shuffle(next.options); turn.correctOptionId = same ? turn.options.find(o => o.isCorrect).id : next.correctOptionId; return changed; }
  function clearRevealTimer(turn) { if (turn.responseRevealTimer) cancelTimer(turn.responseRevealTimer); turn.responseRevealTimer = null; }
  function revealResponse(turn, token) { if (!run || active()?.turn !== turn || token !== turn.audioToken) return; clearRevealTimer(turn); const isFirstReveal = !turn.firstListenCompleted; turn.audioState = "turn"; turn.isInteractive = true; turn.activeRecall = false; turn.firstListenCompleted = true; turn.responseReady = true; turn.responseJustRevealed = isFirstReveal; challenge(false, false); }
  function startActiveRecall(turn, token) { if (!run || active()?.turn !== turn || token !== turn.audioToken || turn.firstListenCompleted) return; clearRevealTimer(turn); turn.isInteractive = false; turn.activeRecall = true; challenge(false, false); turn.responseRevealTimer = schedule(() => revealResponse(turn, token), 1800); }
  function requestAudioRetry(turn, token) { if (!run || active()?.turn !== turn || token !== turn.audioToken || turn.firstListenCompleted) return; turn.isInteractive = false; turn.audioRetryNeeded = true; challenge(false, false); }
  function speakQuestion(turn, current) { const token = ++turn.audioToken, fallback = schedule(() => requestAudioRetry(turn, token), 8000); turn.audioRetryNeeded = false; missionAudio.speakSequence([{ text: current.text, rate: NORMAL_RATE, role: "officer" }]).then(results => { cancelTimer(fallback); if (!run || active()?.turn !== turn || token !== turn.audioToken) return; if (turn.firstListenCompleted) { turn.audioState = "turn"; turn.isInteractive = true; challenge(false, false); return; } const failed = results.some(result => result?.status !== "ended"); if (failed) { if (turn.audioRetryAttempted) revealResponse(turn, token); else requestAudioRetry(turn, token); return; } startActiveRecall(turn, token); }).catch(() => { cancelTimer(fallback); if (!run || active()?.turn !== turn || token !== turn.audioToken) return; if (turn.audioRetryAttempted) revealResponse(turn, token); else requestAudioRetry(turn, token); }); }
  function challenge(speak = true, scrollTop = false) {
    const turn = initTurn(), current = turn.conversation, total = run.picks.length, full = run.group === "full";
    if (speak) { turn.isInteractive = false; turn.audioState = "speaking"; if (!turn.firstListenCompleted) { clearRevealTimer(turn); turn.activeRecall = false; turn.audioRetryNeeded = false; turn.responseReady = false; turn.responseJustRevealed = false; } }
    const status = turn.responseReady ? "輪到你回應" : turn.activeRecall ? "想一下，你會怎麼回答？" : turn.audioRetryNeeded ? "🔊 點一下播放入境官問題" : "🔊 入境官正在詢問你…";
    const heading = full ? `<section class="counter-scene"><p class="counter-kicker">🛂 IMMIGRATION</p><div class="counter-officer"><div class="counter-avatar">👤</div><div><strong>Immigration Officer</strong><small>入境官</small></div></div><p class="counter-audio-state ${turn.activeRecall ? "is-active-recall" : ""}">${status}</p>${turn.officerRephrased ? `<p class="recovery-note">入境官換個方式問你。</p>` : ""}</section>` : `<header class="question-header"><div><p class="eyebrow">ARRIVALS · COUNTER 04</p><h1>入境審查</h1></div><span class="question-count">${run.index + 1} / ${total}</span></header><div class="progress"><span style="width:${(run.index + 1) / total * 100}%"></span></div><div class="officer-stage"><div class="officer-visual">👤</div><div><p class="officer-label">Immigration Officer</p><p class="audio-status ${turn.activeRecall ? "is-active-recall" : ""}">${status}</p></div>${turn.officerRephrased ? `<p class="recovery-note">入境官換個方式問你，再試試看。</p>` : ""}</div>`;
    const audioRetry = turn.audioRetryNeeded ? `<button class="audio-retry" data-a="play-question">🔊 點一下播放入境官問題</button>` : "";
    const assistance = `${turn.subtitle ? `<p class="subtitle question-subtitle">“${current.text}”</p>` : ""}<p class="assistance-copy">沒聽清楚？</p><div class="utility-actions"><button class="utility-button ${turn.repeat ? "is-used" : ""}" data-a="repeat">🔁 再說一次${turn.repeat ? ` <b>${turn.repeat}</b>` : ""}</button><button class="utility-button ${turn.slow ? "is-used" : ""}" data-a="slow">🐢 慢速播放${turn.slow ? ` <b>${turn.slow}</b>` : ""}</button><button class="utility-button ${turn.subtitle ? "is-used" : ""}" data-a="subtitle">CC 英文字幕</button></div>`;
    const travelHint = `<section class="travel-hint"><button class="travel-hint-toggle" data-a="travel-hint" aria-expanded="${turn.travelHintOpen}">📋 旅行資料提示 ${turn.travelHintOpen ? "▴" : "▾"}</button><div class="trip-reference" ${turn.travelHintOpen ? "" : "hidden"}><div class="trip-drawer">${tripRows()}</div></div></section>`;
    const response = `<div class="response-area ${turn.responseReady ? "is-ready" : ""}">${turn.responseReady ? `${full ? `<p class="response-prompt">你要怎麼回應？</p>` : ""}<div class="answers ${turn.responseJustRevealed ? "response-reveal" : ""}">${turn.options.map((o, i) => `<button class="answer" data-a="answer" data-id="${o.id}">${full ? "" : `<span class="choice-letter">${letters[i]}</span>`}${o.text}</button>`).join("")}</div><label class="confidence ${turn.firstAttemptConfidence ? "is-recorded" : ""}"><input id="unsure" type="checkbox" ${turn.firstAttemptConfidence === "unsure" ? "checked" : ""} ${turn.firstAttemptConfidence ? "disabled" : ""}>${turn.firstAttemptConfidence ? "已記錄第一次作答" : "不確定，但我覺得是這個"}</label>` : ""}</div>`;
    renderView(`<section class="screen question-screen ${full ? "full-question-screen" : ""}">${heading}${audioRetry}${assistance}<div class="challenge-bottom">${travelHint}${response}</div></section>`, { scrollTop });
    turn.responseJustRevealed = false;
    if (speak) speakQuestion(turn, current);
  }
  function lock() { document.querySelectorAll('[data-a="answer"],[data-a="repeat"],[data-a="slow"],[data-a="subtitle"]').forEach(button => button.disabled = true); }
  function help(kind) { const turn = initTurn(), waitingForFirstListen = !turn.firstListenCompleted, token = ++turn.audioToken; clearRevealTimer(turn); if (kind === "repeat") turn.repeat++; else turn.slow++; turn.isInteractive = false; turn.audioState = "speaking"; challenge(false, false); lock(); const rate = kind === "slow" ? SLOW_RATE : NORMAL_RATE, finish = results => { if (!run || active()?.turn !== turn || token !== turn.audioToken) return; if (waitingForFirstListen) { const failed = !results || results.some(result => result?.status !== "ended"); if (failed) revealResponse(turn, token); else startActiveRecall(turn, token); return; } turn.audioState = "turn"; turn.isInteractive = true; challenge(false, false); }, fallback = schedule(() => finish(null), 12000), done = results => { cancelTimer(fallback); finish(results); }; missionAudio.speakSequence([{ text: turn.conversation.text, rate, role: "officer" }]).then(done).catch(() => done(null)); }
  function answer(id) { const turn = initTurn(), selected = turn.options.find(o => o.id === id); if (!selected) return; if (!turn.firstAttemptConfidence) { turn.firstAttemptConfidence = document.querySelector("#unsure").checked ? "unsure" : "confident"; turn.firstAttemptCorrect = selected.id === turn.correctOptionId; } if (selected.id === turn.correctOptionId) return complete(selected, true); turn.wrong++; if (turn.wrong <= 2 && turn.conversation.recoveryNext) { const previous = turn.conversation; turn.recoveryLevel++; const changed = setConversation(turn, previous.recoveryNext); turn.officerRephrased = changed && previous.text !== turn.conversation.text; challenge(true, false); return; } complete(selected, false); }
  function advanceAfterComplete(withTransition = true) { if (run.index < run.picks.length) { if (!withTransition) return challenge(true, true); const fullTransition = run.group === "full"; renderView(fullTransition ? `<section class="screen counter-arrival counter-brief"><div class="counter-arrival-visual">👤</div><div class="approach-path"><span></span><span></span><span></span></div></section>` : `<section class="screen approach-screen"><p class="eyebrow">COUNTER 04</p><div class="approach-path"><span></span><span></span><span></span></div></section>`); schedule(() => challenge(true, true), fullTransition ? 380 : 420); } else if (run.group === "full") fullEnding(); else report(); }
  function markCorrectAnswer(optionId) { document.querySelectorAll('[data-a="answer"]').forEach(button => { button.disabled = true; if (button.dataset.id === optionId) button.classList.add("is-correct"); }); }
  function showAdjustmentAndAdvance() { const completedRun = run; renderView(`<section class="screen adjustment-screen"><p>我們下次再調整</p></section>`); schedule(() => { if (run === completedRun) advanceAfterComplete(false); }, 1350); }
  function complete(selected, successful) { const pick = active(), turn = initTurn(), initial = pick.variant, final = turn.conversation, correctOption = final.options.find(option => option.isCorrect), shortAnswer = final.answerType === "action" ? correctOption : final.learnAnswers.simple, fullAnswer = final.learnAnswers.sentence; run.results.push({ scenarioId: pick.scenario.id, variantId: initial.id, finalVariantId: final.id, question: final.text, zh: final.zhMeaning, answer: selected.text, answerZh: selected.zh, shortAnswer: shortAnswer.text, shortAnswerZh: shortAnswer.zh, sentenceAnswer: fullAnswer.text, sentenceAnswerZh: fullAnswer.zh, answerType: final.answerType, firstAttemptConfidence: turn.firstAttemptConfidence, firstAttemptCorrect: turn.firstAttemptCorrect, repeatCount: turn.repeat, slowCount: turn.slow, subtitleUsed: turn.subtitle, wrongAttempts: turn.wrong, recoveryLevel: turn.recoveryLevel, successful, completed: true }); run.index++; if (successful) { const completedRun = run; markCorrectAnswer(selected.id); schedule(() => { if (run === completedRun) advanceAfterComplete(false); }, 450); return; } showAdjustmentAndAdvance(); }
  function fullEnding() { renderView(`<section class="screen rescue-screen full-ending"><p class="eyebrow">🛂 IMMIGRATION</p><div class="counter-scene ending-scene"><div class="counter-officer"><div class="counter-avatar">👤</div><div><strong>Immigration Officer</strong><small>入境官</small></div></div><p class="ending-quote">“All right. You're good to go.”<small>好的，可以通過了。</small></p></div><div class="ending-copy"><strong>✓ 入境審查結束</strong><p>你完成了這次入境互動。</p></div><button class="button button-primary button-large" data-a="full-report">查看這次入境結果 →</button></section>`); missionAudio.speakSequence([{ text: "All right. You're good to go.", rate: NORMAL_RATE, role: "officer" }]); }
  function getScenarioResultStatus(result) { const assisted = result.repeatCount || result.slowCount || result.subtitleUsed || result.recoveryLevel; if (result.firstAttemptCorrect === true && !assisted) return { key: "first_try", label: "第一次就理解" }; if (result.successful === true) return { key: "recovered", label: result.recoveryLevel ? "換個方式後理解" : "使用協助後完成" }; return { key: "needs_practice", label: "這題再練一下" }; }
  const tag = (style, text) => `<span class="status-${style}">${text}</span>`;
  function detail(item, index) { const status = getScenarioResultStatus(item), chips = [item.repeatCount && tag("assist", `重說 ${item.repeatCount}`), item.slowCount && tag("assist", `慢速 ${item.slowCount}`), item.subtitleUsed && tag("assist", "字幕"), item.firstAttemptConfidence === "unsure" && tag("assist", "當時不確定"), item.wrongAttempts && tag("danger", item.wrongAttempts === 3 ? "本題共錯誤 3 次" : `錯誤嘗試 ${item.wrongAttempts}`), item.recoveryLevel && tag("assist", `換個問法 ${item.recoveryLevel}`)].filter(Boolean).join(""); const answerBlock = (label, text, zh, style = "is-muted", playable = true) => `<div class="review-answer ${style}"><span>${label}</span>${playable ? audioButton(text) : ""}<strong>${text}</strong><small>${zh}</small></div>`; const shortLabel = item.answerType === "action" ? "正確動作" : "正確短答", isAction = item.answerType === "action"; return `<article class="review-card result-${status.key}"><div class="review-compact"><div class="result-card-header"><p class="review-number">${String(index + 1).padStart(2, "0")}</p><span class="result-label">${status.label}</span></div><p class="review-english">${audioButton(item.question, "officer", "播放入境官問題")} “${item.question}”</p>${chips ? `<div class="review-status">${chips}</div>` : ""}</div><button class="text-button review-detail-toggle" data-a="item-details" data-id="detail-${index}">查看答案 ▾</button><div id="detail-${index}" hidden><p class="review-copy">${item.zh}</p><div class="review-answer-grid">${answerBlock("你的回答", item.answer, item.answerZh, item.successful ? "is-correct" : "is-incorrect", !isAction)}${answerBlock(shortLabel, item.shortAnswer, item.shortAnswerZh, "is-muted", !isAction)}${answerBlock("也可以這樣完整回答", item.sentenceAnswer, item.sentenceAnswerZh)}</div></div></article>`; }
  function report() { if (run.group === "full") return fullReport(); run.finished = true; const before = progress(), group = run.group, groupIds = ids(group), successfulIds = run.results.filter(item => item.successful).map(item => item.scenarioId); const after = missionStorage.updateProgress({ coreIds: group === "core" ? successfulIds : [], extensionIds: group === "extension" ? successfulIds : [], allCoreIds: ids("core"), allExtensionIds: ids("extension") }); const outcomes = { first_try: 0, recovered: 0, needs_practice: 0 }; run.results.forEach(item => outcomes[getScenarioResultStatus(item).key]++); const mastered = count(after, group), total = groupIds.length; const unlockedNow = group === "core" && !before.extensionUnlocked && after.extensionUnlocked; let actions = ""; if (group === "core" && after.extensionUnlocked) actions = `<div class="unlock-panel"><strong>${unlockedNow ? "核心入境挑戰完成" : "核心入境挑戰已完成"}</strong><p>${unlockedNow ? "你已成功處理 8 個核心入境情境。接下來可以挑戰 4 個新的詢問情境。" : "你可以隨時挑戰 4 個新的延伸詢問情境。"}</p><button class="button button-primary button-large" data-a="simulate-extension">${unlockedNow ? "繼續挑戰｜延伸4情境 →" : "挑戰延伸4情境"}</button><button class="button button-quiet button-large" data-a="replay">再模擬核心8情境</button></div>`; else if (group === "extension" && after.fullSimulationUnlocked) actions = `<div class="unlock-panel"><strong>延伸入境挑戰完成</strong><p>你已成功處理核心8情境與4個延伸情境。完整入境模擬已解鎖。</p><button class="button button-primary button-large" data-a="home">返回首頁查看完整模擬</button></div>`; else actions = `<div class="mastery-panel"><strong>${group === "core" ? "核心入境進度" : "延伸入境進度"} ${mastered} / ${total}</strong><p>還有 ${total - mastered} 個情境就能${group === "core" ? "解鎖延伸挑戰" : "完成延伸挑戰"}。</p><button class="button button-primary button-large" data-a="replay">再挑戰${group === "core" ? "核心8情境" : "延伸4情境"}</button></div>`; renderView(`<section class="screen results-screen"><p class="eyebrow">🛂 ENTRY CLEARED</p><h1>你完成這次<br>${groupName(group)}。</h1><div class="report-summary"><strong>${total} 個情境已完成模擬</strong><div class="report-outcomes"><div class="outcome-first"><span>第一次就理解</span><b>${outcomes.first_try}</b></div><div class="outcome-recovered"><span>換個方式後理解</span><b>${outcomes.recovered}</b></div><div class="outcome-practice"><span>這題再練一下</span><b>${outcomes.needs_practice}</b></div></div></div><button class="review-toggle" data-a="details">查看這次 ${total} 題答案 ▾</button><section class="mission-review" id="details" hidden>${run.results.map(detail).join("")}</section>${actions}<button class="text-button" data-a="home">⌂ 返回首頁</button></section>`); missionStorage.saveChallenge({ schemaVersion: 4, missionId: m.id, group, createdAt: new Date().toISOString(), completed: true, results: run.results }); }
  function fullReport() { run.finished = true; const total = run.results.length, outcomes = { first_try: 0, recovered: 0, needs_practice: 0 }; run.results.forEach(item => outcomes[getScenarioResultStatus(item).key]++); renderView(`<section class="screen results-screen"><p class="eyebrow">🛂 FULL SIMULATION</p><h1>完整入境模擬完成</h1><p class="lead">這次入境官詢問了 ${total} 個情境。</p><div class="report-summary"><div class="report-outcomes"><div class="outcome-first"><span>第一次就理解</span><b>${outcomes.first_try}</b></div><div class="outcome-recovered"><span>換個方式後理解</span><b>${outcomes.recovered}</b></div><div class="outcome-practice"><span>這題再練一下</span><b>${outcomes.needs_practice}</b></div></div></div><button class="review-toggle" data-a="details">查看這次入境對話 ▾</button><section class="mission-review" id="details" hidden>${run.results.map(detail).join("")}</section><button class="button button-primary button-large" data-a="replay-full">再模擬一次</button><p class="replay-note">每次都可能遇到不同的問題與問法。</p><button class="text-button" data-a="home">⌂ 返回首頁</button></section>`); missionStorage.saveFullSimulationAttempt(run.fullScenarioIds); missionStorage.saveChallenge({ schemaVersion: 5, missionId: m.id, group: "full", createdAt: new Date().toISOString(), completed: true, results: run.results }); }
  app.addEventListener("click", event => { const button = event.target.closest("[data-a]"); if (!button || button.disabled) return; const action = button.dataset.a; if (action === "home") requestExitToHome(); else if (action === "continue-exit") closeExitConfirmation(); else if (action === "confirm-exit") exitToHome(); else if (action === "learn") { stopPageActivity(); learn(); } else if (action === "lesson") { stopPageActivity(); lesson(button.dataset.id); } else if (action === "survival") { stopPageActivity(); survival(); } else if (action === "simulate-core") trip("core"); else if (action === "simulate-extension") trip("extension"); else if (action === "full-intro") fullIntro(); else if (action === "start-full") startFull(); else if (action === "start") start(button.dataset.group); else if (action === "replay") start(run.group); else if (action === "replay-full") startFull(); else if (action === "full-report") { stopPageActivity(); report(); } else if (action === "speak") missionAudio.speakSequence([{ text: button.dataset.text, rate: NORMAL_RATE, role: button.dataset.role || "officer" }]); else if (action === "play-question") { const turn = initTurn(); turn.audioRetryAttempted = true; turn.audioRetryNeeded = false; challenge(false, false); speakQuestion(turn, turn.conversation); } else if (action === "repeat") help("repeat"); else if (action === "slow") help("slow"); else if (action === "subtitle") { const turn = initTurn(); turn.subtitle = !turn.subtitle; challenge(false, false); } else if (action === "travel-hint") { const turn = initTurn(); turn.travelHintOpen = !turn.travelHintOpen; challenge(false, false); } else if (action === "answer") answer(button.dataset.id); else if (["details", "item-details", "toggle-variants", "toggle-answers"].includes(action)) { const target = action === "details" ? document.querySelector("#details") : action === "item-details" ? document.querySelector(`#${button.dataset.id}`) : action === "toggle-variants" ? document.querySelector("#more-variants") : document.querySelector("#more-answers"); target.hidden = !target.hidden; button.textContent = target.hidden ? (action === "details" ? (run?.group === "full" ? "查看這次入境對話 ▾" : `查看這次 ${run?.picks.length || ""} 題答案 ▾`) : action === "item-details" ? "查看答案 ▾" : action === "toggle-variants" ? "查看更多問法 ▾" : "查看更多回答 ▾") : (action === "details" ? "收起這次對話 ▴" : action === "item-details" ? "收起答案 ▴" : action === "toggle-variants" ? "收起其他問法 ▴" : "收起其他回答 ▴"); } });
  home();
})();
